version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pytest src/functions.py -v
          name: Test
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test